// Türkçe özeti yazınız.
Genişletilmiş Türkçe özeti, tez hazırlama kılavuzunda verilen açıklamaları dikkate alarak yazınız. ……………………………… …………………………………………………………………………………………………………………………………………………………………………………… ……………………………………………………………………………………………………………………………………………………
