#import "/src/core/language-manager/language-manager.typ": translator
#import "/src/constants/language-keys.typ": language-keys

/*
TR-TR: Türkçe (Türkiye) [Turkish (Türkiye)]\
EN-US: İngilizce (ABD) [English (US)]
*/
#let LANGUAGES = (
  TR-TR: (
    language-code: "tr",
    region-code: "tr",
  ),
  EN-US: (
    language-code: "en",
    region-code: "us",
  ),
)

/*
MASTER-THESIS-PROPOSAL: "Yüksek Lisans Tez Önerisi"\
MASTER-THESIS: "Yüksek Lisans Tezi"\
DOCTORAL-THESIS-PROPOSAL: "Doktora Tez Önerisi"\
DOCTORAL-THESIS: "Doktora Tezi"\
TERM-PROJECT: "Dönem Projesi"
*/
#let REPORT-TYPES = (
  MASTER-THESIS-PROPOSAL: translator(key: language-keys.MASTER-THESIS-PROPOSAL),
  MASTER-THESIS: translator(key: language-keys.MASTER-THESIS),
  DOCTORAL-THESIS-PROPOSAL: translator(key: language-keys.DOCTORAL-THESIS-PROPOSAL),
  DOCTORAL-THESIS: translator(key: language-keys.DOCTORAL-THESIS),
  TERM-PROJECT: translator(key: language-keys.TERM-PROJECT),
)

/*
TODO
*/
#let ACADEMIC-MEMBER-TITLES = (
  __ACADEMIC-MEMBER-TITLE-PLACE-HOLDER: translator(key: language-keys.ACADEMIC-MEMBER-TITLE-PLACE-HOLDER),
  ASSISTANT-PROFESSOR-DR: translator(key: language-keys.ASSISTANT-PROFESSOR-DR),
  ASSOCIATE-PROFESSOR-DR: translator(key: language-keys.ASSOCIATE-PROFESSOR-DR),
  PROFESSOR: translator(key: language-keys.PROFESSOR),
  PROFESSOR-DR: translator(key: language-keys.PROFESSOR-DR),
)

// Ana Bilim Dalları [Departments]
#let DEPARTMENTS = (
  __DEPARTMENT-PLACE-HOLDER: translator(key: language-keys.DEPARTMENT-PLACE-HOLDER),
  DEPARTMENT-OF-PHYSICAL-EDUCATION-AND-SPORTS: translator(
    key: language-keys.DEPARTMENT-OF-PHYSICAL-EDUCATION-AND-SPORTS,
  ),
  DEPARTMENT-OF-COMPUTER-EDUCATION-AND-INSTRUCTIONAL-TECHNOLOGY: translator(
    key: language-keys.DEPARTMENT-OF-COMPUTER-EDUCATION-AND-INSTRUCTIONAL-TECHNOLOGY,
  ),
  DEPARTMENT-OF-EDUCATIONAL-SCIENCES: translator(key: language-keys.DEPARTMENT-OF-EDUCATIONAL-SCIENCES),
  DEPARTMENT-OF-CURRICULUM-AND-INSTRUCTION: translator(key: language-keys.DEPARTMENT-OF-CURRICULUM-AND-INSTRUCTION),
  DEPARTMENT-OF-FINE-ARTS-EDUCATION: translator(key: language-keys.DEPARTMENT-OF-FINE-ARTS-EDUCATION),
  DEPARTMENT-OF-ELEMENTARY-EDUCATION: translator(key: language-keys.DEPARTMENT-OF-ELEMENTARY-EDUCATION),
  DEPARTMENT-OF-ELEMENTARY-RELIGIOUS-CULTURE-AND-ETHICS-EDUCATION: translator(
    key: language-keys.DEPARTMENT-OF-ELEMENTARY-RELIGIOUS-CULTURE-AND-ETHICS-EDUCATION,
  ),
  DEPARTMENT-OF-MATHEMATICS-AND-SCIENCES-EDUCATION: translator(
    key: language-keys.DEPARTMENT-OF-MATHEMATICS-AND-SCIENCES-EDUCATION,
  ),
  DEPARTMENT-OF-SECONDARY-SCIENCE-AND-MATHEMATICS-EDUCATION: translator(
    key: language-keys.DEPARTMENT-OF-SECONDARY-SCIENCE-AND-MATHEMATICS-EDUCATION,
  ),
  DEPARTMENT-OF-SECONDARY-SOCIAL-SCIENCES-EDUCATION: translator(
    key: language-keys.DEPARTMENT-OF-SECONDARY-SOCIAL-SCIENCES-EDUCATION,
  ),
  DEPARTMENT-OF-SPECIAL-EDUCATION: translator(key: language-keys.DEPARTMENT-OF-SPECIAL-EDUCATION),
  DEPARTMENT-OF-BASIC-EDUCATION: translator(key: language-keys.DEPARTMENT-OF-BASIC-EDUCATION),
  DEPARTMENT-OF-TURKISH-EDUCATION: translator(key: language-keys.DEPARTMENT-OF-TURKISH-EDUCATION),
  DEPARTMENT-OF-TURKISH-AND-SOCIAL-SCIENCES-EDUCATION: translator(
    key: language-keys.DEPARTMENT-OF-TURKISH-AND-SOCIAL-SCIENCES-EDUCATION,
  ),
  DEPARTMENT-OF-FOREIGN-LANGUAGE-EDUCATION: translator(key: language-keys.DEPARTMENT-OF-FOREIGN-LANGUAGE-EDUCATION),
)

// Bilim Dalları [Programs]
#let PROGRAMS = (
  __PROGRAM-PLACE-HOLDER: translator(key: language-keys.PROGRAM-PLACE-HOLDER),
  GERMAN-LANGUAGE-EDUCATION-PROGRAM: translator(key: language-keys.GERMAN-LANGUAGE-EDUCATION-PROGRAM),
  PHYSICAL-EDUCATION-AND-SPORTS-PROGRAM: translator(key: language-keys.PHYSICAL-EDUCATION-AND-SPORTS-PROGRAM),
  COMPUTER-EDUCATION-AND-INSTRUCTIONAL-TECHNOLOGY-PROGRAM: translator(
    key: language-keys.COMPUTER-EDUCATION-AND-INSTRUCTIONAL-TECHNOLOGY-PROGRAM,
  ),
  BIOLOGY-EDUCATION-PROGRAM: translator(key: language-keys.BIOLOGY-EDUCATION-PROGRAM),
  GEOGRAPHY-EDUCATION-PROGRAM: translator(key: language-keys.GEOGRAPHY-EDUCATION-PROGRAM),
  CURRICULUM-AND-INSTRUCTION-PROGRAM: translator(key: language-keys.CURRICULUM-AND-INSTRUCTION-PROGRAM),
  EDUCATION-MANAGEMENT-PROGRAM: translator(key: language-keys.EDUCATION-MANAGEMENT-PROGRAM),
  EDUCATIONAL-ADMINISTRATION-SUPERVISION-PLANNING-AND-ECONOMICS-PROGRAM: translator(
    key: language-keys.EDUCATIONAL-ADMINISTRATION-SUPERVISION-PLANNING-AND-ECONOMICS-PROGRAM,
  ),
  PHILOSOPHY-EDUCATION-PROGRAM: translator(key: language-keys.PHILOSOPHY-EDUCATION-PROGRAM),
  SCIENCE-EDUCATION-PROGRAM: translator(key: language-keys.SCIENCE-EDUCATION-PROGRAM),
  PHYSICS-EDUCATION-PROGRAM: translator(key: language-keys.PHYSICS-EDUCATION-PROGRAM),
  ELEMENTARY-RELIGIOUS-CULTURE-AND-ETHICS-EDUCATION-PROGRAM: translator(
    key: language-keys.ELEMENTARY-RELIGIOUS-CULTURE-AND-ETHICS-EDUCATION-PROGRAM,
  ),
  ELEMENTARY-MATHEMATICS-EDUCATION-PROGRAM: translator(key: language-keys.ELEMENTARY-MATHEMATICS-EDUCATION-PROGRAM),
  ENGLISH-LANGUAGE-EDUCATION-PROGRAM: translator(key: language-keys.ENGLISH-LANGUAGE-EDUCATION-PROGRAM),
  CHEMISTRY-EDUCATION-PROGRAM: translator(key: language-keys.CHEMISTRY-EDUCATION-PROGRAM),
  MATHEMATICS-EDUCATION-PROGRAM: translator(key: language-keys.MATHEMATICS-EDUCATION-PROGRAM),
  MUSIC-EDUCATION-PROGRAM: translator(key: language-keys.MUSIC-EDUCATION-PROGRAM),
  PRESCHOOL-EDUCATION-PROGRAM: translator(key: language-keys.PRESCHOOL-EDUCATION-PROGRAM),
  SPECIAL-EDUCATION-PROGRAM: translator(key: language-keys.SPECIAL-EDUCATION-PROGRAM),
  LEADERSHIP-AND-MANAGEMENT-IN-SPECIAL-TEACHING-INSTITUTIONS-PROGRAM: translator(
    key: language-keys.LEADERSHIP-AND-MANAGEMENT-IN-SPECIAL-TEACHING-INSTITUTIONS-PROGRAM,
  ),
  GUIDANCE-AND-PSYCHOLOGICAL-COUNSELING-PROGRAM: translator(
    key: language-keys.GUIDANCE-AND-PSYCHOLOGICAL-COUNSELING-PROGRAM,
  ),
  ART-EDUCATION-PROGRAM: translator(key: language-keys.ART-EDUCATION-PROGRAM),
  PRIMARY-EDUCATION-PROGRAM: translator(key: language-keys.PRIMARY-EDUCATION-PROGRAM),
  SOCIAL-STUDIES-EDUCATION-PROGRAM: translator(key: language-keys.SOCIAL-STUDIES-EDUCATION-PROGRAM),
  HISTORY-EDUCATION-PROGRAM: translator(key: language-keys.HISTORY-EDUCATION-PROGRAM),
  TURKISH-LANGUAGE-AND-LITERATURE-EDUCATION-PROGRAM: translator(
    key: language-keys.TURKISH-LANGUAGE-AND-LITERATURE-EDUCATION-PROGRAM,
  ),
  TURKISH-EDUCATION-PROGRAM: translator(key: language-keys.TURKISH-EDUCATION-PROGRAM),
  TEACHING-TURKISH-TO-FOREIGNERS-PROGRAM: translator(key: language-keys.TEACHING-TURKISH-TO-FOREIGNERS-PROGRAM),
  TURKISH-TEACHING-TO-TURKISH-CHILDREN-ABROAD-PROGRAM: translator(
    key: language-keys.TURKISH-TEACHING-TO-TURKISH-CHILDREN-ABROAD-PROGRAM,
  ),
  MENTALLY-DISABLED-EDUCATION-PROGRAM: translator(key: language-keys.MENTALLY-DISABLED-EDUCATION-PROGRAM),
)
