// Numaralandırma [Numbering]
#let PAGE-NUMBERING-ROMAN = "i" // Sayfalar [Pages]
#let PAGE-NUMBERING-ARABIC = "1" // Sayfalar [Pages]
#let HEADING-NUMBERING = "1.1." // Başlıklar [Headings]
#let FIGURE-NUMBERING = "1.1" // Simgeler [Figures]
#let MATH-NUMBERING = "(1.1)" // Matematik Denklemleri [Math Equations]
#let LIST-NUMBERING = "1." // Numaralı Listeler [Numbered Lists]
#let FOOTNOTE-NUMBERING = "1" // Dipnotlar [Footnotes]
