// Türkçe özeti yazınız.
Özet metnini, tez hazırlama kılavuzunda verilen açıklamaları dikkate alarak yazınız. ……………………………… …………………………………………………………………………………………………………………………………………………………………………………… ……………………………………………………………………………………………………………………………………………………
